default_settings: null
behaviors:
  EatPrey:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0008
      beta: 0.005
      epsilon: 0.2
      lambd: 0.9
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.85
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 90
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
      curiosity:
        gamma: 0.85
        strength: 0.04
        network_settings:
          normalize: false
          hidden_units: 90
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
        learning_rate: 0.0008
      # gail:
      #   gamma: 0.9
      #   strength: 0.3
      #   demo_path: \unityProjects\AI_cell_battle\venv\Demos
      #   network_settings:
      #     normalize: false
      #     hidden_units: 90
      #     num_layers: 2
      #     vis_encode_type: simple
      #     memory: null
      #     goal_conditioning_type: hyper
      #   learning_rate: 0.0008
    init_path: null
    keep_checkpoints: 3
    checkpoint_interval: 250000
    max_steps: 800000
    time_horizon: 128
    summary_freq: 25000
    threaded: false
    self_play: null
    behavioral_cloning: null
    
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 0
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
torch_settings:
  device: null
debug: false